version: '3.1'

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx-apploud-gitlab
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./:/var/www/website/
    links:
      - php74
    ports:
      - 8080:80
      - 3000:443
  php74:
    build: ./docker/php-fpm
    container_name: php-apploud-gitlab
    volumes:
      - ./:/var/www/website/
    ports:
      - 9003:9000